name: Kairos builder

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  KAIROS_VERSION: v3.1.1
  FLAVOR: ubuntu

permissions:
  contents: read
  packages: write

jobs:
  image-builder:
    name: Build Kairos image
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ^0.8.0
      - uses: actions/checkout@v4
        with:
          repository: kairos-io/kairos
          ref: ${{ env.KAIROS_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: build iso image
        run: earthly +all-arm-generic --FAMILY=ubuntu --FLAVOR=${{ env.FLAVOR }} --FLAVOR_RELEASE=24.04 --BASE_IMAGE=${{ env.FLAVOR }}:24.04 --VARIANT=standard
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retag and push image
        run: |
          export _NEW_TAG=ghcr.io/${{ github.repository }}/${{ env.FLAVOR }}:$(cat build/IMAGE | cut -f2 -d:)
          echo $_NEW_TAG
          docker tag $(cat build/IMAGE) $_NEW_TAG
          docker push $_NEW_TAG
